url = https://demoqa.com/

ElementBtn=//div[@class='category-cards']//div[@class='card mt-4 top-card']

textBox=//*[contains(text(),'Text Box')]
names=userName
usermails=userEmail

adresscurrent=currentAddress
permanentadress=permanentAddress
buttonSub=submit

formsbtn=//*[contains(text(),'Forms')]
praticeForms=//*[contains(text(),'Practice Form')]
namepracticetext=//input[@id='firstName']
lasttextpractise=//input[@id='lastName']
mailpractise=//input[@id='userEmail']
cochepractise=//input[@id='gender-radio-2']
textpractise=//input[@id='userNumber']
dateofbrith=dateOfBirthInput
dateofbirths=//select[@class='react-datepicker__month-select']

pagetextelement=//div[@id='section1Content']/p

elementBtnwighets=//*[contains(text(),'Widgets')]

elementes=//span[@class='group-header'][1]
addbutton=//button[@id='addNewRecordButton']
webtables=//*[contains(text(),'Web Tables')]
firstname=//input[@id='firstName']
lastname=//input[@id='lastName']
usermail=//input[@id='userEmail']
ages=//input[@id='age']
salary=//input[@id='salary']
dept=//input[@id='department']
sub=//button[@id='submit']